### ISSUE TITLE
Help import

### ISSUE THREAD

**Issue by Ngochuy238** [exsilium/ogy#49]
![image](https://github.com/exsilium/ogy/assets/127245358/42f54532-6734-4618-820b-633cfb8328c5)
I haven't edited, just imported. What did I do wrong? Help help......

**Comment by exsilium** [comment]
If you run `npm test`, does the test suite complete successfully? I have not tested this on Windows, I'd need to try to reproduce this issue.

**Comment by exsilium** [comment]
@Ngochuy238 , confirmed not to be working on Windows. I'll try to get to the bottom of it this week and land a fix for it. 🎸

**Comment by exsilium** [comment]
For additional context, the DICT_J.bin included the following headers:

```
§Tipode Ponteiro=Informação de Cartas=C:\Users\XxX\Projects\ogy\test\CARD_Indx_J.bin = C:\Users\XxX\Projects\ogy\test\DICT_J.bin<PONTEIRO: 0,0>
§Tipode Ponteiro=Informação de Cartas=/mnt/c/Users/XxX/Projects/ogy/test/CARD_Indx_J.bin = /mnt/c/Users/XxX/Projects/ogy/test/DICT_J.bin<PONTEIRO: 0,0>
```
